image: "rust:latest"

stages:
- info
- test
# - deps
- build

cache:
  paths:
  - apt/
  - cargo/
  - target/

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

info:
  stage: info
  script:
  - rustc --version
  - cargo --version

test:
  stage: test
  script:
  - cargo test

# deps:
#   stage: deps
#   script:
#   - cargo build

build:
  stage: build
  script:
  - cargo build
