image: "rust:latest"

stages:
- info
- deps
- test
- panic
- build

cache:
  paths:
  - apt/
  - cargo/
  - target/

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

info:
  stage: info
  script:
  - rustc --version
  - cargo --version

deps:
  allow_failure: true
  stage: deps
  script:
  - cargo install --git https://github.com/Technolution/rustig rustig || echo "rustig already installed"

test:
  stage: test
  script:
  - cargo test

panic:
  allow_failure: true
  stage: panic
  script:
  - cargo build --example hello
  - cd ./target/debug/examples
  - rustig -b ./hello

build:
  stage: build
  script:
  - cargo build
